const dummyRoomBooking = [
  {
    roomId: "1",
    location: {
      city: "YVR",
      building: "32",
      floor: 1,
      roomCode: "101",
      roomName: "Stanley",
    },
    equipments: ["AV", "VC"],
    numSeat: 4,
    is_active: true,
  },
  {
    roomId: "2",
    location: {
      city: "YVR",
      building: "32",
      floor: 1,
      roomCode: "404",
      roomName: "Lighthouse",
    },
    equipments: ["AV", "VC"],
    numSeat: 18,
    is_active: true,
  },
  {
    roomId: "3",
    location: {
      city: "YVR",
      building: "32",
      floor: 2,
      roomCode: "103",
      roomName: "Gastown",
    },
    equipments: ["AV, VC"],
    numSeat: 4,
    is_active: true,
  },
  {
    roomId: "4",
    location: {
      city: "YVR",
      building: "32",
      floor: 5,
      roomCode: "103",
      roomName: "Chinook",
    },
    equipments: ["AV, VC"],
    numSeat: 16,
    is_active: true,
  },
  {
    roomId: "5",
    location: {
      city: "YVR",
      building: "41",
      floor: 4,
      roomCode: "102",
      roomName: "Conference Room",
    },
    equipments: ["AV, VC"],
    numSeat: 12,
    is_active: true,
  },
  {
    roomId: "6",
    location: {
      city: "YVR",
      building: "74",
      floor: 1,
      roomCode: "400",
      roomName: "Bugaboo",
    },
    equipments: ["AV", "VC"],
    numSeat: 4,
    is_active: true,
  },
  {
    roomId: "7",
    location: {
      city: "YVR",
      building: "74",
      floor: 2,
      roomCode: "100",
      roomName: "Grouse",
    },
    equipments: ["AV", "VC"],
    numSeat: 4,
    is_active: true,
  },
  {
    roomId: "8",
    location: {
      city: "YVR",
      building: "74",
      floor: 4,
      roomCode: "300",
      roomName: "Alice",
    },
    equipments: ["AV", "VC"],
    numSeat: 8,
    is_active: true,
  },
  {
    roomId: "9",
    location: {
      city: "YVR",
      building: "74",
      floor: 7,
      roomCode: "100",
      roomName: "Waterfront",
    },
    equipments: ["AV", "VC"],
    numSeat: 4,
    is_active: true,
  },
  {
    roomId: "10",
    location: {
      city: "YVR",
      building: "74",
      floor: 7,
      roomCode: "101",
      roomName: "Vancouver",
    },
    equipments: ["VC"],
    numSeat: 4,
    is_active: true,
  },
  {
    roomId: "11",
    location: {
      city: "YVR",
      building: "74",
      floor: 7,
      roomCode: "300",
      roomName: "Oakridge",
    },
    equipments: ["AV", "VC"],
    numSeat: 8,
    is_active: true,
  },
  {
    roomId: "12",
    location: {
      city: "YVR",
      building: "74",
      floor: 7,
      roomCode: "402",
      roomName: "Granville",
    },
    equipments: ["AV"],
    numSeat: 14,
    is_active: true,
  },
];

export default dummyRoomBooking;
